#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set keyboard
setxkbmap es

#set monitor ouputs
xrandr --output DVI-I-1 --mode 1024x768 --output VGA-1 --mode 1600x900 --left-of DVI-I-1


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#Background
feh --bg-fill ~/Desktop/yuri.jpg


#set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

